<a href="https://colab.research.google.com/github/rajp152k/Machine_Learning/blob/master/models%20-%20udemy%20course/Deep%20Learning/ANN/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the Dataset

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [0]:
import io
dataset = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

## Data Preprocessing

In [6]:
dataset

RowNumber  CustomerId  ... EstimatedSalary  Exited
0             1    15634602  ...       101348.88       1
1             2    15647311  ...       112542.58       0
2             3    15619304  ...       113931.57       1
3             4    15701354  ...        93826.63       0
4             5    15737888  ...        79084.10       0
5             6    15574012  ...       149756.71       1
6             7    15592531  ...        10062.80       0
7             8    15656148  ...       119346.88       1
8             9    15792365  ...        74940.50       0
9            10    15592389  ...        71725.73       0
10           11    15767821  ...        80181.12       0
11           12    15737173  ...        76390.01       0
12           13    15632264  ...        26260.98       0
13           14    15691483  ...       190857.79       0
14           15    15600882  ...        65951.65       0
15           16    15643966  ...        64327.26       0
16           17    15737452  ...         5097.67       1
17           18    15788218  ...        14406.41       0
18           19    15661507  ...       158684.81       0
19           20    15568982  ...        54724.03       0
20           21    15577657  ...       170886.17       0
21           22    15597945  ...       138555.46       0
22           23    15699309  ...       118913.53       1
23           24    15725737  ...         8487.75       0
24           25    15625047  ...       187616.16       0
25           26    15738191  ...       124508.29       0
26           27    15736816  ...       170041.95       0
27           28    15700772  ...        38433.35       0
28           29    15728693  ...       100187.43       0
29           30    15656300  ...        53483.21       0
...         ...         ...  ...             ...     ...
9970       9971    15587133  ...       119377.36       0
9971       9972    15721377  ...       166472.81       0
9972       9973    15747927  ...       171552.02       0
9973       9974    15806455  ...       157474.10       0
9974       9975    15695474  ...        13549.24       0
9975       9976    15666295  ...       196526.55       1
9976       9977    15656062  ...        84419.78       0
9977       9978    15579969  ...        24991.92       0
9978       9979    15703563  ...       191608.97       0
9979       9980    15692664  ...         2988.28       0
9980       9981    15719276  ...        99595.67       0
9981       9982    15672754  ...        53445.17       1
9982       9983    15768163  ...       115146.40       1
9983       9984    15656710  ...       151325.24       0
9984       9985    15696175  ...        51695.41       0
9985       9986    15586914  ...        96833.00       0
9986       9987    15581736  ...        34047.54       0
9987       9988    15588839  ...         1914.41       0
9988       9989    15589329  ...        49337.84       0
9989       9990    15605622  ...       179436.60       0
9990       9991    15798964  ...        53667.08       0
9991       9992    15769959  ...        69384.71       1
9992       9993    15657105  ...       195192.40       0
9993       9994    15569266  ...        29179.52       0
9994       9995    15719294  ...       167773.55       0
9995       9996    15606229  ...        96270.64       0
9996       9997    15569892  ...       101699.77       0
9997       9998    15584532  ...        42085.58       1
9998       9999    15682355  ...        92888.52       1
9999      10000    15628319  ...        38190.78       0

[10000 rows x 14 columns]

don't need the customer id, surname and row number in the dependent variable matrix

In [0]:
X = dataset.iloc[:,3:-1].values

In [0]:
Y = dataset.iloc[:,-1].values

Preparing matrix of featues(encoding and handling dummy variables)

In [0]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [0]:
L_encoder_x1 = LabelEncoder()
L_encoder_x2 = LabelEncoder()

In [0]:
X[:,1] = L_encoder_x1.fit_transform(X[:,1])
X[:,2] = L_encoder_x2.fit_transform(X[:,2])

In [30]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
OHcoder = OneHotEncoder(categorical_features = [1])

In [32]:
X = OHcoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [34]:
pd.DataFrame(X)

0    1    2      3    4   ...         7    8    9    10         11
0     1.0  0.0  0.0  619.0  0.0  ...       0.00  1.0  1.0  1.0  101348.88
1     0.0  0.0  1.0  608.0  0.0  ...   83807.86  1.0  0.0  1.0  112542.58
2     1.0  0.0  0.0  502.0  0.0  ...  159660.80  3.0  1.0  0.0  113931.57
3     1.0  0.0  0.0  699.0  0.0  ...       0.00  2.0  0.0  0.0   93826.63
4     0.0  0.0  1.0  850.0  0.0  ...  125510.82  1.0  1.0  1.0   79084.10
5     0.0  0.0  1.0  645.0  1.0  ...  113755.78  2.0  1.0  0.0  149756.71
6     1.0  0.0  0.0  822.0  1.0  ...       0.00  2.0  1.0  1.0   10062.80
7     0.0  1.0  0.0  376.0  0.0  ...  115046.74  4.0  1.0  0.0  119346.88
8     1.0  0.0  0.0  501.0  1.0  ...  142051.07  2.0  0.0  1.0   74940.50
9     1.0  0.0  0.0  684.0  1.0  ...  134603.88  1.0  1.0  1.0   71725.73
10    1.0  0.0  0.0  528.0  1.0  ...  102016.72  2.0  0.0  0.0   80181.12
11    0.0  0.0  1.0  497.0  1.0  ...       0.00  2.0  1.0  0.0   76390.01
12    1.0  0.0  0.0  476.0  0.0  ...       0.00  2.0  1.0  0.0   26260.98
13    1.0  0.0  0.0  549.0  0.0  ...       0.00  2.0  0.0  0.0  190857.79
14    0.0  0.0  1.0  635.0  0.0  ...       0.00  2.0  1.0  1.0   65951.65
15    0.0  1.0  0.0  616.0  1.0  ...  143129.41  2.0  0.0  1.0   64327.26
16    0.0  1.0  0.0  653.0  1.0  ...  132602.88  1.0  1.0  0.0    5097.67
17    0.0  0.0  1.0  549.0  0.0  ...       0.00  2.0  1.0  1.0   14406.41
18    0.0  0.0  1.0  587.0  1.0  ...       0.00  1.0  0.0  0.0  158684.81
19    1.0  0.0  0.0  726.0  0.0  ...       0.00  2.0  1.0  1.0   54724.03
20    1.0  0.0  0.0  732.0  1.0  ...       0.00  2.0  1.0  1.0  170886.17
21    0.0  0.0  1.0  636.0  0.0  ...       0.00  2.0  1.0  0.0  138555.46
22    0.0  0.0  1.0  510.0  0.0  ...       0.00  1.0  1.0  0.0  118913.53
23    1.0  0.0  0.0  669.0  1.0  ...       0.00  2.0  0.0  1.0    8487.75
24    1.0  0.0  0.0  846.0  0.0  ...       0.00  1.0  1.0  1.0  187616.16
25    1.0  0.0  0.0  577.0  1.0  ...       0.00  2.0  0.0  1.0  124508.29
26    0.0  1.0  0.0  756.0  1.0  ...  136815.64  1.0  1.0  1.0  170041.95
27    1.0  0.0  0.0  571.0  1.0  ...       0.00  2.0  0.0  0.0   38433.35
28    0.0  1.0  0.0  574.0  0.0  ...  141349.43  1.0  1.0  1.0  100187.43
29    1.0  0.0  0.0  411.0  1.0  ...   59697.17  2.0  1.0  1.0   53483.21
...   ...  ...  ...    ...  ...  ...        ...  ...  ...  ...        ...
9970  1.0  0.0  0.0  518.0  1.0  ...  151027.05  2.0  1.0  0.0  119377.36
9971  1.0  0.0  0.0  833.0  0.0  ...  144751.81  1.0  0.0  0.0  166472.81
9972  1.0  0.0  0.0  758.0  1.0  ...  155739.76  1.0  1.0  0.0  171552.02
9973  1.0  0.0  0.0  611.0  1.0  ...       0.00  2.0  1.0  1.0  157474.10
9974  1.0  0.0  0.0  583.0  1.0  ...  122531.86  1.0  1.0  0.0   13549.24
9975  0.0  1.0  0.0  610.0  1.0  ...  113957.01  2.0  1.0  0.0  196526.55
9976  1.0  0.0  0.0  637.0  0.0  ...  103377.81  1.0  1.0  0.0   84419.78
9977  1.0  0.0  0.0  683.0  0.0  ...       0.00  2.0  1.0  1.0   24991.92
9978  1.0  0.0  0.0  774.0  1.0  ...   93017.47  2.0  1.0  0.0  191608.97
9979  1.0  0.0  0.0  677.0  0.0  ...   90022.85  1.0  0.0  1.0    2988.28
9980  0.0  0.0  1.0  741.0  1.0  ...   74371.49  1.0  0.0  0.0   99595.67
9981  0.0  1.0  0.0  498.0  1.0  ...  152039.70  1.0  1.0  1.0   53445.17
9982  0.0  1.0  0.0  655.0  0.0  ...  137145.12  1.0  1.0  0.0  115146.40
9983  1.0  0.0  0.0  613.0  1.0  ...       0.00  1.0  0.0  0.0  151325.24
9984  0.0  1.0  0.0  602.0  1.0  ...   90602.42  2.0  1.0  1.0   51695.41
9985  1.0  0.0  0.0  659.0  1.0  ...  123841.49  2.0  1.0  0.0   96833.00
9986  0.0  1.0  0.0  673.0  1.0  ...  183579.54  2.0  0.0  1.0   34047.54
9987  0.0  0.0  1.0  606.0  1.0  ...  180307.73  2.0  1.0  1.0    1914.41
9988  1.0  0.0  0.0  775.0  1.0  ...       0.00  2.0  1.0  0.0   49337.84
9989  0.0  0.0  1.0  841.0  1.0  ...       0.00  2.0  1.0  1.0  179436.60
9990  0.0  1.0  0.0  714.0  1.0  ...   35016.60  1.0  1.0  0.0   53667.08
9991  1.0  0.0  0.0  597.0  0.0  ...   88381.21  1.0  1.0  0.0   69384.71
9992  0.0  

Dropping the first column of X(dummy var trap)

In [0]:
X = X[:,1:]

In [37]:
pd.DataFrame(X)

0    1      2    3     4     5          6    7    8    9          10
0     0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0  101348.88
1     0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0  112542.58
2     0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0  113931.57
3     0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   93826.63
4     0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   79084.10
5     0.0  1.0  645.0  1.0  44.0   8.0  113755.78  2.0  1.0  0.0  149756.71
6     0.0  0.0  822.0  1.0  50.0   7.0       0.00  2.0  1.0  1.0   10062.80
7     1.0  0.0  376.0  0.0  29.0   4.0  115046.74  4.0  1.0  0.0  119346.88
8     0.0  0.0  501.0  1.0  44.0   4.0  142051.07  2.0  0.0  1.0   74940.50
9     0.0  0.0  684.0  1.0  27.0   2.0  134603.88  1.0  1.0  1.0   71725.73
10    0.0  0.0  528.0  1.0  31.0   6.0  102016.72  2.0  0.0  0.0   80181.12
11    0.0  1.0  497.0  1.0  24.0   3.0       0.00  2.0  1.0  0.0   76390.01
12    0.0  0.0  476.0  0.0  34.0  10.0       0.00  2.0  1.0  0.0   26260.98
13    0.0  0.0  549.0  0.0  25.0   5.0       0.00  2.0  0.0  0.0  190857.79
14    0.0  1.0  635.0  0.0  35.0   7.0       0.00  2.0  1.0  1.0   65951.65
15    1.0  0.0  616.0  1.0  45.0   3.0  143129.41  2.0  0.0  1.0   64327.26
16    1.0  0.0  653.0  1.0  58.0   1.0  132602.88  1.0  1.0  0.0    5097.67
17    0.0  1.0  549.0  0.0  24.0   9.0       0.00  2.0  1.0  1.0   14406.41
18    0.0  1.0  587.0  1.0  45.0   6.0       0.00  1.0  0.0  0.0  158684.81
19    0.0  0.0  726.0  0.0  24.0   6.0       0.00  2.0  1.0  1.0   54724.03
20    0.0  0.0  732.0  1.0  41.0   8.0       0.00  2.0  1.0  1.0  170886.17
21    0.0  1.0  636.0  0.0  32.0   8.0       0.00  2.0  1.0  0.0  138555.46
22    0.0  1.0  510.0  0.0  38.0   4.0       0.00  1.0  1.0  0.0  118913.53
23    0.0  0.0  669.0  1.0  46.0   3.0       0.00  2.0  0.0  1.0    8487.75
24    0.0  0.0  846.0  0.0  38.0   5.0       0.00  1.0  1.0  1.0  187616.16
25    0.0  0.0  577.0  1.0  25.0   3.0       0.00  2.0  0.0  1.0  124508.29
26    1.0  0.0  756.0  1.0  36.0   2.0  136815.64  1.0  1.0  1.0  170041.95
27    0.0  0.0  571.0  1.0  44.0   9.0       0.00  2.0  0.0  0.0   38433.35
28    1.0  0.0  574.0  0.0  43.0   3.0  141349.43  1.0  1.0  1.0  100187.43
29    0.0  0.0  411.0  1.0  29.0   0.0   59697.17  2.0  1.0  1.0   53483.21
...   ...  ...    ...  ...   ...   ...        ...  ...  ...  ...        ...
9970  0.0  0.0  518.0  1.0  42.0   7.0  151027.05  2.0  1.0  0.0  119377.36
9971  0.0  0.0  833.0  0.0  34.0   3.0  144751.81  1.0  0.0  0.0  166472.81
9972  0.0  0.0  758.0  1.0  26.0   4.0  155739.76  1.0  1.0  0.0  171552.02
9973  0.0  0.0  611.0  1.0  27.0   7.0       0.00  2.0  1.0  1.0  157474.10
9974  0.0  0.0  583.0  1.0  33.0   7.0  122531.86  1.0  1.0  0.0   13549.24
9975  1.0  0.0  610.0  1.0  50.0   1.0  113957.01  2.0  1.0  0.0  196526.55
9976  0.0  0.0  637.0  0.0  33.0   7.0  103377.81  1.0  1.0  0.0   84419.78
9977  0.0  0.0  683.0  0.0  32.0   9.0       0.00  2.0  1.0  1.0   24991.92
9978  0.0  0.0  774.0  1.0  40.0   9.0   93017.47  2.0  1.0  0.0  191608.97
9979  0.0  0.0  677.0  0.0  58.0   1.0   90022.85  1.0  0.0  1.0    2988.28
9980  0.0  1.0  741.0  1.0  35.0   6.0   74371.49  1.0  0.0  0.0   99595.67
9981  1.0  0.0  498.0  1.0  42.0   3.0  152039.70  1.0  1.0  1.0   53445.17
9982  1.0  0.0  655.0  0.0  46.0   7.0  137145.12  1.0  1.0  0.0  115146.40
9983  0.0  0.0  613.0  1.0  40.0   4.0       0.00  1.0  0.0  0.0  151325.24
9984  1.0  0.0  602.0  1.0  35.0   7.0   90602.42  2.0  1.0  1.0   51695.41
9985  0.0  0.0  659.0  1.0  36.0   6.0  123841.49  2.0  1.0  0.0   96833.00
9986  1.0  0.0  673.0  1.0  47.0   1.0  183579.54  2.0  0.0  1.0   34047.54
9987  0.0  1.0  606.0  1.0  30.0   8.0  180307.73  2.0  1.0  1.0    1914.41
9988  0.0  0.0  775.0  1.0  30.0   4.0       0.00  2.0  1.0  0.0   49337.84
9989  0.0  1.0  841.0  1.0  28.0   4.0       0.00  2.0  1.0  1.0  179436.60
9990  1.0  0.0  714.0  1.0  33.0   3.0   35016.60  1.0 

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size= 0.2,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_scaler = StandardScaler()
X_train = X_scaler.fit_transform(X_train)
X_test = X_scaler.transform(X_test)

## Creating the ANN

In [45]:
import keras

Using TensorFlow backend.


In [0]:
from keras.models import Sequential
from keras.layers import Dense

## Sequential for initializing the neural network 
## Dense for adding layers to the network

initializing the ANN by defining it as a sequence of layers<br>
creating a classifier

In [0]:
classifier = Sequential()

input layer has 11 nodes (no. of cols in feature matrix)

for the hidden layers, choosing the activating function to be a rectifier, whereas for the final output node, choosing sigmoid as its activation function to get a probability

For now, the hidden layer is chosen to have 6 nodes, will consider the effect of this when reassess this implementation during studying parameter tuning

In [67]:
classifier.add(Dense(units=6,input_dim = 11, activation="relu",kernel_initializer="uniform"))

W0820 16:52:57.990065 139822000064384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 16:52:57.994730 139822000064384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [0]:
classifier.add(Dense(units=6, activation="relu",kernel_initializer="uniform"))

no need to add the input dim as we already have inserted the first layer 

adding the output layer now

In [0]:
classifier.add(Dense(units=1,activation="sigmoid",kernel_initializer="uniform"))

for the final output layer having more than 2 nodes, we use the softmax activation function(sigmoid for multiclassification)

## applying Stochastic gradient descent

In [70]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics = ["accuracy"] )

W0820 16:53:07.893055 139822000064384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0820 16:53:07.900048 139822000064384 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


adam is a sort of a stochastic gradient descent algorithm <br>
binary_crossentropy is used as a loss function for binary classification and multiple_crossentropy for poly-classification

In [73]:
classifier.fit(X_train,Y_train,batch_size=10,nb_epoch=100)

Epoch 1/100
1360/8000 [====>.........................] - ETA: 0s - loss: 0.4557 - acc: 0.7934

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 1s 119us/step - loss: 0.4359 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4284 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4217 - acc: 0.8145
Epoch 4/100
8000/8000 [==============================] - 1s 111us/step - loss: 0.4156 - acc: 0.8286
Epoch 5/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4109 - acc: 0.8315
Epoch 6/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4079 - acc: 0.8347
Epoch 7/100
8000/8000 [==============================] - 1s 112us/step - loss: 0.4057 - acc: 0.8329
Epoch 8/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4042 - acc: 0.8327
Epoch 9/100
8000/8000 [==============================] - 1s 113us/step - loss: 0.4029 - acc: 0.8357
Epoch 10/100
8000/8000 [==============================] - 1s 115us/step - loss: 0.4017 - acc: 0.8346
Epoch 11/10

In [0]:
Y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix

as Y_pred is the result of a sigmoid activation function, it returns probabilities, hence we need to discretize it<br>
could use 
   ```
   Y_pred = (Y_pred>threshold)
   ```
   for an inplace update rather than looping as below

In [0]:
Y_pred_discrete = []
for i in Y_pred:
    if i>=0.5:
        Y_pred_discrete.append(1)
    else:
        Y_pred_discrete.append(0)
Y_pred_discrete = np.asarray(Y_pred_discrete)

In [90]:
Y_pred

array([[0.34268147],
       [0.59164083],
       [0.4045655 ],
       ...,
       [0.3675595 ],
       [0.23226231],
       [0.2942559 ]], dtype=float32)

In [91]:
Y_pred_discrete

array([0, 1, 0, ..., 0, 0, 0])

In [0]:
cm = confusion_matrix(Y_test,Y_pred_discrete)

In [93]:
cm

array([[1283,  312],
       [ 143,  262]])

In [0]:
accuracy = (1283+262)/(2000)

In [95]:
accuracy

0.7725