In [1]:
import numpy as np

In [6]:
data  = np.random.randn(2,2)

In [7]:
data

array([[0.66828088, 0.71981523],
       [1.30235738, 0.08472933]])

In [9]:
print(data+data)

[[1.33656176 1.43963046]
 [2.60471477 0.16945867]]


In [17]:
print(data*10)

[[ 6.68280882  7.19815231]
 [13.02357384  0.84729334]]


In [18]:
data1 = [1,2,3,4,5,6]

In [19]:
arr1 = np.array(data1)

In [20]:
print(arr1)

[1 2 3 4 5 6]


In [21]:
data2 = [2,3,4,5,6,7]

In [23]:
data3 = [data1,data2]

In [24]:
data3

[[1, 2, 3, 4, 5, 6], [2, 3, 4, 5, 6, 7]]

In [25]:
arr2 = np.array(data3)

In [26]:
arr2

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [27]:
arr2.shape

(2, 6)

In [28]:
arr2.dtype

dtype('int32')

In [37]:
arr3 = np.arange(10)

In [38]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr3.dtype

dtype('int32')

In [45]:
arr4 = np.ones_like(arr3)

In [51]:
arr4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
arr5 = np.full((2,2),5)

In [60]:
print(arr5,arr5.dtype)

[[5 5]
 [5 5]] int32


In [63]:
arr6 = arr5.astype(bool)

In [64]:
print(arr6)

[[ True  True]
 [ True  True]]


In [65]:
arr5[1][1] = False

In [66]:
arr6 = arr5.astype(bool)

In [67]:
print(arr6)

[[ True  True]
 [ True False]]


In [68]:
list = ['34','45']

In [74]:
arr7 = np.array(['34','45'],dtype=np.string_)

In [75]:
arr7

array([b'34', b'45'], dtype='|S2')

In [76]:
arr7.astype(float)

array([34., 45.])

In [77]:
list

['34', '45']

In [80]:
arr8 = np.array((list,list))

In [81]:
arr8

array([['34', '45'],
       ['34', '45']], dtype='<U2')

In [82]:
arr8 = arr8.astype(np.float64)

In [83]:
arr8

array([[34., 45.],
       [34., 45.]])

In [84]:
arr8*arr8

array([[1156., 2025.],
       [1156., 2025.]])

In [85]:
arr8/arr8

array([[1., 1.],
       [1., 1.]])

In [89]:
arr9 = np.random.randn(4,4,4)

In [99]:
names = ['raj','alice','bob','cathy','daisy','eustace','raj']
names = np.array(names)

In [111]:
arr9 = np.random.randn(7,2,1)
arr9

array([[[-0.04412397],
        [-0.79257942]],

       [[-0.92851876],
        [ 1.23612029]],

       [[ 1.91345293],
        [-1.25259063]],

       [[ 0.8734028 ],
        [-0.46875102]],

       [[ 1.51026719],
        [-0.77283164]],

       [[-2.06741164],
        [-0.79856692]],

       [[-1.8846442 ],
        [ 0.17709434]]])

In [112]:
names == 'raj'

array([ True, False, False, False, False, False,  True])

In [118]:
arr10 = arr9[names=='raj',:1].copy()

In [119]:
arr10

array([[[-0.04412397]],

       [[-1.8846442 ]]])

In [122]:
arr11 = np.empty((10,10))

In [124]:
for i in range(10):
    arr11[:,i] = i**2


In [125]:
arr11

array([[ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.],
       [ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.]])

In [126]:
arr11[:,[2,3,1,0]]

array([[4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.],
       [4., 9., 1., 0.]])

In [127]:
arr12 = np.arange(30).reshape((6,5))

In [129]:
arr12+1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [130]:
(arr12+1).T

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [132]:
np.dot(arr12.T,arr12)

array([[1375, 1450, 1525, 1600, 1675],
       [1450, 1531, 1612, 1693, 1774],
       [1525, 1612, 1699, 1786, 1873],
       [1600, 1693, 1786, 1879, 1972],
       [1675, 1774, 1873, 1972, 2071]])

In [134]:
arr12.transpose(0,1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [135]:
arr12.transpose(1,0)

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])