In [1]:
import numpy as np
x = np.random.randn(3,3)
y = np.random.randn(3,3)

In [2]:
np.dot(x,y)

array([[-1.067751  , -0.88634254, -1.48398097],
       [-1.12478013, -1.15116268, -0.55696477],
       [-2.28566386, -2.19731754, -2.42695773]])

In [4]:
x@y
#similar to np.dot()

array([[-1.067751  , -0.88634254, -1.48398097],
       [-1.12478013, -1.15116268, -0.55696477],
       [-2.28566386, -2.19731754, -2.42695773]])

In [5]:
from numpy.linalg import inv,qr

In [6]:
x = np.random.randn(5,5)

In [7]:
mat = np.dot(x.T,x)

In [14]:
ans = np.array(np.dot(mat,inv(mat))

In [16]:
ans

array([[ 1.00000000e+00,  2.15532264e-17,  1.09524888e-16,
         3.42345437e-17, -1.24896778e-16],
       [-8.91542267e-17,  1.00000000e+00, -3.38873712e-15,
         9.24706763e-16,  3.77721820e-15],
       [-4.39058198e-17, -2.12840581e-16,  1.00000000e+00,
        -3.34968751e-16,  8.08200750e-16],
       [ 5.64637085e-17, -3.65087256e-16, -1.13739347e-15,
         1.00000000e+00, -3.51894328e-15],
       [ 3.52201805e-17, -3.20026257e-17, -6.43572487e-16,
         3.46345177e-16,  1.00000000e+00]])

In [31]:
x = np.random.randn(5,5);y = np.random.randn(5,1)
np.linalg.solve(x,y)

array([[-0.13303703],
       [-0.24529856],
       [-0.29469247],
       [-0.39613598],
       [ 0.16225913]])

In [32]:
np.linalg.lstsq(x,y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([[-0.13303703],
        [-0.24529856],
        [-0.29469247],
        [-0.39613598],
        [ 0.16225913]]),
 array([], dtype=float64),
 5,
 array([3.56196434, 2.91707932, 2.65438084, 0.8395099 , 0.67283584]))